"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Eye, RefreshCw, TrendingDown, TrendingUp, UserPlus, Users } from "lucide-react";
import { superadminFetch } from "../../utils/superadmin-api-client";

type Point = { date: string; visitors: number; newVisitors: number; pageViews: number };
type Analytics = { series: Point[]; topPages: { path: string; views: number; visitors: number }[]; totalVisitors: number; periodVisitors: number; periodPageViews: number; previousPeriodVisitors: number; previousPeriodPageViews: number };
const EMPTY: Analytics = { series: [], topPages: [], totalVisitors: 0, periodVisitors: 0, periodPageViews: 0, previousPeriodVisitors: 0, previousPeriodPageViews: 0 };

export default function SuperadminAnalyticsPage() {
  const [days, setDays] = useState(30);
  const [customDays, setCustomDays] = useState("30");
  const [data, setData] = useState<Analytics>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData({ ...EMPTY, ...await superadminFetch<Analytics>(`/api/superadmin/analytics?days=${days}`) }); } catch (e) { setError(e instanceof Error ? e.message : "Chargement impossible."); } finally { setLoading(false); } }, [days]);
  useEffect(() => { void load(); }, [load]);
  const today = data.series.at(-1) || { visitors: 0, newVisitors: 0, pageViews: 0, date: "" };
  const max = Math.max(1, ...data.series.map((point) => point.visitors));
  const series = useMemo(() => days === 90 ? data.series.filter((_, index) => index % 3 === 0 || index === data.series.length - 1) : data.series, [data.series, days]);
  const change = (now: number, before: number) => before ? Math.round(((now - before) / before) * 100) : now ? 100 : 0;
  const exportCsv = () => { const rows = [["Date","Visiteurs uniques","Nouveaux visiteurs","Pages vues"],...data.series.map((p) => [p.date,p.visitors,p.newVisitors,p.pageViews])]; const url=URL.createObjectURL(new Blob([rows.map((r)=>r.join(";")).join("\n")],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a"); a.href=url;a.download=`analytics-nexa-${days}-jours.csv`;a.click();URL.revokeObjectURL(url); };
  const cards = [{ label: "Visiteurs aujourd’hui", value: today.visitors, icon: Users },{ label: "Nouveaux aujourd’hui", value: today.newVisitors, icon: UserPlus },{ label: `Visiteurs sur ${days} jours`, value: data.periodVisitors, icon: TrendingUp },{ label: `Pages vues sur ${days} jours`, value: data.periodPageViews, icon: Eye }];
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black text-white">Audience du site</h2><p className="mt-1 text-sm text-slate-400">Visiteurs anonymes, acquisition et contenus consultés.</p></div><div className="flex flex-wrap gap-2">{[7,30,90].map((period)=><button key={period} onClick={()=>setDays(period)} className={`rounded-lg px-3 py-2 text-xs font-black ${days===period?"bg-orange-500 text-white":"border border-white/10 bg-white/5 text-slate-400"}`}>{period} j</button>)}<form onSubmit={(e)=>{e.preventDefault();setDays(Math.max(7,Math.min(Number(customDays)||30,90)));}} className="flex"><input type="number" min="7" max="90" value={customDays} onChange={(e)=>setCustomDays(e.target.value)} className="w-16 rounded-l-lg border border-white/10 bg-white/5 px-2 text-xs text-white outline-none" /><button className="rounded-r-lg border border-l-0 border-white/10 px-2 text-[10px] font-bold text-slate-400">jours</button></form><button onClick={exportCsv} aria-label="Exporter CSV" className="rounded-lg border border-white/10 p-2 text-slate-400"><Download className="h-4 w-4" /></button><button onClick={()=>void load()} aria-label="Actualiser" className="rounded-lg border border-white/10 p-2 text-slate-400"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`} /></button></div></div>
    {error ? <div className="rounded-2xl border border-red-500/20 bg-red-500/10 p-5 text-sm text-red-300">{error}<button onClick={()=>void load()} className="ml-3 rounded-lg bg-red-500/15 px-3 py-2 text-xs font-black">Réessayer</button></div> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon})=><div key={label} className="rounded-2xl border border-white/10 bg-[#0a0f1c] p-5"><Icon className="h-5 w-5 text-orange-400" /><p className="mt-3 text-[10px] font-black uppercase tracking-widest text-slate-500">{label}</p>{loading?<div className="mt-2 h-8 w-20 animate-pulse rounded-lg bg-white/5"/>:<p className="mt-1 text-3xl font-black text-white">{value.toLocaleString("fr-FR")}</p>}</div>)}</div>
      <div className="grid gap-3 sm:grid-cols-2">{[{label:"Visiteurs",value:change(data.periodVisitors,data.previousPeriodVisitors)},{label:"Pages vues",value:change(data.periodPageViews,data.previousPeriodPageViews)}].map((item)=><div key={item.label} className="flex items-center justify-between rounded-2xl border border-white/10 bg-[#0a0f1c] p-5"><div><p className="text-xs font-bold text-slate-400">Évolution · {item.label}</p><p className="text-[10px] text-slate-600">Période précédente</p></div><span className={`flex items-center gap-1 text-xl font-black ${item.value>=0?"text-emerald-400":"text-red-400"}`}>{item.value>=0?<TrendingUp className="h-4 w-4"/>:<TrendingDown className="h-4 w-4"/>}{item.value>0?"+":""}{item.value}%</span></div>)}</div>
      <div className="rounded-2xl border border-white/10 bg-[#0a0f1c] p-5"><div className="flex justify-between"><div><h3 className="font-black text-white">Visiteurs par jour</h3><p className="text-xs text-slate-500">Orange : uniques · Vert : nouveaux</p></div><p className="text-xs font-bold text-slate-500">{data.totalVisitors} au total</p></div><div className="mt-6 flex h-64 items-end gap-1 border-b border-white/10">{series.map((point)=><div key={point.date} className="group flex h-full min-w-3 flex-1 items-end gap-px" title={`${point.date}: ${point.visitors} visiteurs`}><div className="w-2/3 rounded-t bg-orange-500/80" style={{height:`${Math.max(3,(point.visitors/max)*90)}%`}}/><div className="w-1/3 rounded-t bg-emerald-400/80" style={{height:`${Math.max(3,(point.newVisitors/max)*90)}%`}}/></div>)}</div></div>
      <div className="rounded-2xl border border-white/10 bg-[#0a0f1c] p-5"><h3 className="font-black text-white">Pages les plus consultées</h3><div className="mt-3 divide-y divide-white/[0.07]">{data.topPages.length===0&&<p className="py-8 text-center text-sm text-slate-500">Les données apparaîtront après les premières visites.</p>}{data.topPages.map((page,index)=><div key={page.path} className="flex items-center gap-3 py-3"><span className="w-6 text-xs font-black text-slate-600">{index+1}</span><span className="min-w-0 flex-1 truncate text-sm font-bold text-slate-200">{page.path}</span><span className="text-xs text-slate-500">{page.visitors} visiteurs</span><span className="w-20 text-right text-sm font-black text-white">{page.views} vues</span></div>)}</div></div>
    </>}
  </div>;
}
