export const sharedDocuments = {
  fr: {
    formationsHeroTitle: "Formations NEXA", formationsHeroSubtitle: "Explorez notre catalogue et développez de nouvelles compétences.", formationsActiveSectionTitle: "Vos accès actifs",
    formationsMainBadge: "Formation principale", formationsMainCourseTitle: "TCF Canada Intensive", formationsMainCourseDescription: "Préparation complète : Écrit, Oral, Simulateur NEXA.", formationsStatusLabel: "Statut", formationsStatusInProgress: "En cours", formationsContinueButton: "Continuer",
    formationsUpcomingSectionTitle: "À venir", formationsComingSoonBadge: "Bientôt", formationsObjectiveLabel: "Objectif", formationsLockedLabel: "Verrouillé", formationsUpcomingAlertPrefix: "La formation", formationsUpcomingAlertSuffix: "est en cours de création. Restez à l’écoute !",
    formationsAnglaisTitle: "Anglais (IELTS / TOEFL)", formationsAnglaisDescription: "Maîtrisez la langue de Shakespeare pour vos projets internationaux et professionnels.", formationsAnglaisLevel: "A1 au C1", formationsAllemandTitle: "Allemand (Goethe)", formationsAllemandDescription: "Atteignez le niveau B2 exigé pour étudier, vivre ou travailler en Allemagne.", formationsAllemandLevel: "A1 au B2", formationsChinoisTitle: "Chinois (HSK)", formationsChinoisDescription: "Ouvrez-vous les portes de l’Asie avec notre méthode d’apprentissage accélérée.", formationsChinoisLevel: "HSK 1 à 4",
    documentLoginRequired: "Connectez-vous pour ouvrir ce document.", documentNotFoundError: "Document introuvable.", documentLoadFileError: "Impossible de charger le fichier.", documentGenericLoadError: "Erreur de chargement.", documentExternalLinkError: "Impossible d’ouvrir ce lien externe.", documentTitleFallback: "Document", documentPdfTitleFallback: "document", documentDownloadButton: "Télécharger", documentReadOnlyLabel: "Lecture seule", documentLoadingLabel: "Chargement du document…", documentFileReadyLabel: "Fichier prêt.", documentDownloadDisabledMessage: "Ce cours n’autorise pas le téléchargement. Ouvrez le document depuis la leçon en lecture seule.", documentBackButton: "Retour",
    certificatNotFoundTitle: "Certificat introuvable", certificatNotFoundMessage: "Ce certificat n’existe pas ou n’est plus disponible.", certificatAuthenticTitle: "Certificat authentique", certificatIssuedByLabel: "Délivré par NEXA", certificatCandidateLabel: "Candidat :", certificatSubjectLabel: "Objet :", certificatIssuedOnLabel: "Délivré le :", certificatCodeLabel: "Code de vérification :",
  },
  en: {
    formationsHeroTitle: "NEXA Courses", formationsHeroSubtitle: "Explore our catalog and develop new skills.", formationsActiveSectionTitle: "Your active access",
    /* TCF content intentionally remains in French. */
    formationsMainBadge: "Formation principale", formationsMainCourseTitle: "TCF Canada Intensive", formationsMainCourseDescription: "Préparation complète : Écrit, Oral, Simulateur NEXA.", formationsStatusLabel: "Status", formationsStatusInProgress: "In progress", formationsContinueButton: "Continue",
    formationsUpcomingSectionTitle: "Coming soon", formationsComingSoonBadge: "Coming soon", formationsObjectiveLabel: "Target", formationsLockedLabel: "Locked", formationsUpcomingAlertPrefix: "The", formationsUpcomingAlertSuffix: "course is currently being created. Stay tuned!",
    formationsAnglaisTitle: "English (IELTS / TOEFL)", formationsAnglaisDescription: "Master English for your international and professional goals.", formationsAnglaisLevel: "A1 to C1", formationsAllemandTitle: "German (Goethe)", formationsAllemandDescription: "Reach the B2 level required to study, live, or work in Germany.", formationsAllemandLevel: "A1 to B2", formationsChinoisTitle: "Chinese (HSK)", formationsChinoisDescription: "Open the door to Asia with our accelerated learning method.", formationsChinoisLevel: "HSK 1 to 4",
    documentLoginRequired: "Sign in to open this document.", documentNotFoundError: "Document not found.", documentLoadFileError: "Unable to load the file.", documentGenericLoadError: "Loading error.", documentExternalLinkError: "Unable to open this external link.", documentTitleFallback: "Document", documentPdfTitleFallback: "document", documentDownloadButton: "Download", documentReadOnlyLabel: "Read only", documentLoadingLabel: "Loading document…", documentFileReadyLabel: "File ready.", documentDownloadDisabledMessage: "This course does not allow downloads. Open the document from the lesson in read-only mode.", documentBackButton: "Back",
    certificatNotFoundTitle: "Certificate not found", certificatNotFoundMessage: "This certificate does not exist or is no longer available.", certificatAuthenticTitle: "Authentic certificate", certificatIssuedByLabel: "Issued by NEXA", certificatCandidateLabel: "Candidate:", certificatSubjectLabel: "Subject:", certificatIssuedOnLabel: "Issued on:", certificatCodeLabel: "Verification code:",
  },
} as const;
